"""add users groups items delegations

Revision ID: 533e74d956e2
Revises: b7c2a8f1d4e9
Create Date: 2026-06-04 19:43:07.293781

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "533e74d956e2"
down_revision: Union[str, Sequence[str], None] = "b7c2a8f1d4e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("role", sa.Enum("admin", "user", name="userrole"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    op.add_column("items", sa.Column("location", sa.String(), nullable=True))
    op.add_column("items", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.add_column(
        "items",
        sa.Column("owner_group_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "fk_items_owner_id_users", "items", "users", ["owner_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_items_owner_group_id_groups",
        "items",
        "groups",
        ["owner_group_id"],
        ["id"],
    )
    op.create_table(
        "delegations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column(
            "permission",
            sa.Enum("manage", "edit", name="permissionlevel"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delegations")
    op.drop_constraint("fk_items_owner_group_id_groups", "items", type_="foreignkey")
    op.drop_constraint("fk_items_owner_id_users", "items", type_="foreignkey")
    op.drop_column("items", "owner_group_id")
    op.drop_column("items", "owner_id")
    op.drop_column("items", "location")
    op.drop_table("group_members")
    op.drop_table("users")
    op.drop_table("groups")
    # ### end Alembic commands ###
